# **02. Pandas**

In [ ]:
import pandas as pd

## **02.1. Introduccion**
Para importar la libreria pandas `import pandas as pd`

### **02.1.1. Creacion de datos**

#### **02.1.1.1. DataFrame**
Son tablas que contienen entradas individuales las cuales cada celda tiene un valor, y cada fila (o registro) es una entrada, y tiene columnas, es como una tabla en SQL.

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

#### **02.1.1.2. Series**
Son una secuencia de valores, si un DataFrame es una tabla, una Serie es una lista, de echo se crean con nada mas ni nada menos que una lista.

In [ ]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

### **02.1.2. Leer archivos de datos**
Pandas permite leer archivos .csv para crear DataFrames y Series.

- `read_csv()`: permite leer un archivo para interpretarlo con pandas.
- `shape`: permite ver el tamaño total del contenido del archivo csv.

In [58]:
wine_reviews = pd.read_csv("./archivosDeDatos/winemag-data-130k-v2.csv")
wine_reviews.shape

(119988, 15)

In [59]:
wine_reviews.head() #ver las cinco primeras filas del archivo csv

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

 - `read_csv("",index_col=NUMERO):` permite leer un archivo, pero reinterpreta la primera fila que era la del numero de fila.

In [ ]:
wine_reviews = pd.read_csv("./archivosDeDatos/winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

## **02.2. Indexacion, Seleccion y Asignacion**

### **02.2.1. Accesos nativos (indexacion en Python)**
Metodos de acceso a datos que estan integrados en el nucleo de Python, no son tan utiles como los de Pandas pero son mas rapidos en algun aspecto en concreto.

In [31]:
reviews = pd.read_csv("./archivosDeDatos/winemag-data-130k-v2.csv", index_col=0)

In [11]:
reviews.country

0         Austria
1              US
2              US
3           Spain
4           Spain
           ...
119983      Italy
119984      Italy
119985      Italy
119986         US
119987    Austria
Name: country, Length: 119988, dtype: object

- `dataframe['VALOR']`: devuelve solo una columna de datos.

In [32]:
reviews['country']

id
94355     Austria
126883         US
119493         US
126909      Spain
119752      Spain
           ...
80210       Italy
76487       Italy
86953       Italy
18824          US
88999     Austria
Name: country, Length: 119988, dtype: object

- `dataframe['VALOR'][INDICE]`: devuelve solo el valor de la columna seleccionada.

In [97]:
reviews['country'][0]

'Italy'

#### **02.2.2. Indexacion en pandas**
`iloc` es mejor indexando por indices ya que utiliza la libreria estandar de Python.

**NOTA:** Tanto `loc` como `iloc` siguen el orden «primero la fila, luego la columna». Esto es lo contrario de lo que hacemos en Python nativo, donde el orden es «primero la columna, luego la fila».

Esto significa que resulta ligeramente más fácil recuperar filas y ligeramente más difícil recuperar columnas.

##### **02.2.2.1. Seleccion basada en indices**
Recoger datos mediante la posicion que ocupan en la tabla.

In [34]:
reviews.iloc[0] #selecciona la primera fila

country                                                            Austria
description              "Chremisa," the ancient name of Krems, is comm...
designation                                  Edition Chremisa Sandgrube 13
points                                                                  85
price                                                                 24.0
province                                                  Niederösterreich
region_1                                                               NaN
region_2                                                               NaN
taster_name                                                     Roger Voss
taster_twitter_handle                                           @vossroger
title                    Winzer Krems 2011 Edition Chremisa Sandgrube 1...
variety                                                   Grüner Veltliner
winery                                                        Winzer Krems
dupe?                                                                  NaN
Name: 94355, dtype: object

In [35]:
reviews.iloc[:, 0] #selecciona toda la primera columna

id
94355     Austria
126883         US
119493         US
126909      Spain
119752      Spain
           ...
80210       Italy
76487       Italy
86953       Italy
18824          US
88999     Austria
Name: country, Length: 119988, dtype: object

In [36]:
reviews.iloc[:3, 0] # selecciona los tres primeros valores

id
94355     Austria
126883         US
119493         US
Name: country, dtype: object

In [37]:
reviews.iloc[1:3, 0] #selecciona de la 1 a la 3 por posicion

id
126883    US
119493    US
Name: country, dtype: object

In [38]:
reviews.iloc[[0, 1, 2], 0] #seleeciona 3 entradas en concreto

id
94355     Austria
126883         US
119493         US
Name: country, dtype: object

In [39]:
reviews.iloc[-5:] #selecciona las ultimas 5 entradas de la tabla

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

##### **02.2.2.2. Seleccion basada en etiquetas**
Seleccionar datos mediante alguna "etiqueta" que tengan, refiriendome a etiqueta como el nombre de una columna o el nombre de un valor de alguna columna.

In [61]:
reviews.loc[0, 'country'] #seleccion del primer valor que hay en la columna "country"

'Italy'

In [63]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']] #devuelve los valores de estas tres columnas solo

              taster_name taster_twitter_handle  points
id
94355          Roger Voss            @vossroger      85
126883     Virginie Boone               @vboone      87
119493                NaN                   NaN      86
126909  Michael Schachner           @wineschach      86
119752  Michael Schachner           @wineschach      87
...                   ...                   ...     ...
80210                 NaN                   NaN      90
76487                 NaN                   NaN      88
86953                 NaN                   NaN      90
18824      Virginie Boone               @vboone      87
88999    Anne Krebiehl MW           @AnneInVino      90

[119988 rows x 3 columns]

##### **02.2.2.3. Elegir entre `loc` e `iloc`**
A la hora de elegir o cambiar entre `loc` e `iloc`, hay un «matiz» que conviene tener en cuenta: ambos métodos utilizan esquemas de indexación ligeramente diferentes.

`iloc` utiliza el esquema de indexación de la biblioteca estándar de Python, en el que se incluye el primer elemento del rango y se excluye el último. Por lo tanto, 0:10 seleccionará las entradas 0, ..., 9. loc, por su parte, indexa de forma inclusiva. Así, 0:10 seleccionará las entradas 0, ..., 10.

¿A qué se debe este cambio? Recuerda que loc puede indexar cualquier tipo de la biblioteca estándar: cadenas, por ejemplo. Si tenemos un DataFrame con valores de índice Apples, ..., «Potatoes», …, y queremos seleccionar «todas las frutas en orden alfabético entre Apples y Potatoes», resulta mucho más cómodo indexar df.loc[“Apples”:'Potatoes'] que indexar algo como df.loc[“Apples”, “Potatoet”] (la «t» viene después de la «s» en el alfabeto).

Esto resulta especialmente confuso cuando el índice del DataFrame es una simple lista numérica, por ejemplo, 0,...,1000. En este caso, df.iloc[0:1000] devolverá 1000 entradas, mientras que df.loc[0:1000] devolverá 1001. Para obtener 1000 elementos utilizando `loc`, tendrás que bajar un valor y solicitar `df.loc[0:999]`.

Por lo demás, la semántica del uso de `loc` es la misma que la de `iloc`.

#### **02.2.3. Manipulacion de los indices**
Ya que los indices son muy importantes, estos se pueden manipular para poder escoger esos datos de mejor manera mas tarde.

In [65]:
reviews.set_index("title") #cambio de nombre del indice de la primera columna

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,dupe?
title,,,,,,,,,,,,,
Winzer Krems 2011 Edition Chremisa Sandgrube 13 Grüner Veltliner (Niederösterreich),Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Grüner Veltliner,Winzer Krems,NaN
Line 39 2009 Cabernet Sauvignon (North Coast),US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Cabernet Sauvignon,Line 39,NaN
Jamieson Ranch 2011 Whiplash Chardonnay (California),US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Chardonnay,Jamieson Ranch,NaN
Emilio Moro 2009 Finca Resalso (Ribera del Duero),Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Tinto Fino,Emilio Moro,NaN
La Caña 2010 Albariño (Rías Baixas),Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ceretto 2004 Zonchera (Barolo),Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Nebbiolo,Ceretto,NaN
Zonin 2006 Amarone della Valpolicella,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,"Corvina, Rondinella, Molinara",Zonin,NaN
Zorzettig 2006 Picolit (Colli Orientali del Friuli),Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Picolit,Zorzettig,NaN
Zucca 2010 Sangiovese Rosato Rosé (Amador County),US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Rosé,Zucca,NaN
Nittnaus Hans und Christine 2013 Heideboden Zweigelt (Burgenland),Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Zweigelt,Nittnaus Hans und Christine,NaN

#### **02.2.4. Seleccion condicional**
Seleccion de datos mediante alguna condicion que representen estos.

In [66]:
reviews.country == 'Italy' #aparecen con valores booleanos como True los que si son de Italia y False como los que no son de alli

id
94355     False
126883    False
119493    False
126909    False
119752    False
          ...
80210      True
76487      True
86953      True
18824     False
88999     False
Name: country, Length: 119988, dtype: bool

In [74]:
reviews.loc[reviews.country == 'Italy'] #interpretacion de los datos del anterior comando

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
4515,Italy,95 Massolino 2012 Parafada (Barolo). A textb...,Parafada,95,96.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Massolino 2012 Parafada (Barolo),Nebbiolo,Massolino,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,Italy,Zibibbo is usually presented as a passito dess...,NaN,86,35.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Barraco 2010 Zibibbo (Sicilia),Zibibbo,Barraco,NaN
70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

In [75]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)] #se usa el & para unir dos preguntas

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
4515,Italy,95 Massolino 2012 Parafada (Barolo). A textb...,Parafada,95,96.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Massolino 2012 Parafada (Barolo),Nebbiolo,Massolino,NaN
81278,Italy,"A 25th anniversary special selection, this bea...",Selezione XXV Anno,93,60.0,Tuscany,Brunello di Montalcino,NaN,NaN,NaN,Castello Romitorio 2006 Selezione XXV Anno (B...,Sangiovese Grosso,Castello Romitorio,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54397,Italy,Zenato is a reliable producer of quality Amaro...,NaN,92,30.0,Veneto,Amarone della Valpolicella Classico,NaN,NaN,NaN,Zenato 2008 Amarone della Valpolicella Classico,"Corvina, Rondinella, Molinara",Zenato,NaN
59349,Italy,Zenato's rich and powerful Recioto opens with ...,500 ml,90,NaN,Veneto,Recioto della Valpolicella Classico,NaN,NaN,NaN,Zenato 2006 500 ml (Recioto della Valpolicell...,"Corvina, Rondinella, Molinara",Zenato,NaN
70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

In [70]:
reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)] #se usa el | el cual es el operador logico OR sirve para decir que se cumpla una cosa o la otra

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
29339,US,). Very good wine from a winery increasingly k...,Rockpile Ridge Vineyard,92,47.0,California,Rockpile,Sonoma,NaN,NaN,Mauritson 2009 Rockpile Ridge Vineyard Caberne...,Cabernet Sauvignon,Mauritson,NaN
98444,US,). Vineyard 7&8's Spring Mountain Estate Caber...,Estate,94,125.0,California,Spring Mountain District,Napa,NaN,NaN,Vineyard 7&8 2009 Estate Cabernet Sauvignon (S...,Cabernet Sauvignon,Vineyard 7&8,NaN
60042,US,). You'll want to cellar this young 100% Cab b...,Family Reserve,93,145.0,California,Napa Valley,Napa,NaN,NaN,Venge 2010 Family Reserve Cabernet Sauvignon (...,Cabernet Sauvignon,Venge,NaN
62258,US,. A delightfully intriguing “White Burgundy” b...,White Burgundy,90,29.0,California,North Coast,North Coast,Virginie Boone,@vboone,Imagery 2009 White Burgundy White (North Coast),White Blend,Imagery,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129643,US,Zocker flies under the radar with this Austria...,Paragon Vineyard,90,20.0,California,Edna Valley,Central Coast,NaN,NaN,Zocker 2012 Paragon Vineyard Grüner Veltliner ...,Grüner Veltliner,Zocker,NaN
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [76]:
reviews.loc[reviews.country.isin(['Italy', 'France'])] #pandas tiene algun operador logico incluido como `isin()` el cual comprueba si estan incluidos los valores que se le pasan dentro del conjunto de datos (csv)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
101344,France,. Recent vintages have left Bordeaux with an a...,NaN,87,17.0,Bordeaux,Bordeaux Supérieur,NaN,Roger Voss,@vossroger,Château Sainte-Barbe 2010 Bordeaux Supérieur,Bordeaux-style Red Blend,Château Sainte-Barbe,NaN
23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98934,France,Zind-Humbrecht owns some great Grand Cru viney...,Clos Saint Urbain Rangen de Thann Grand Cru,94,105.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Zind-Humbrecht 2012 Clos Saint Urbain ...,Pinot Gris,Domaine Zind-Humbrecht,NaN
70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

In [77]:
reviews.loc[reviews.price.notnull()] #operador logico de pandas el cual muestra los valores que no son nulos dentro del conjunto de datos (el archivo csv)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
id,,,,,,,,,,,,,,
94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129643,US,Zocker flies under the radar with this Austria...,Paragon Vineyard,90,20.0,California,Edna Valley,Central Coast,NaN,NaN,Zocker 2012 Paragon Vineyard Grüner Veltliner ...,Grüner Veltliner,Zocker,NaN
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

#### **02.2.5. Asignacion de datos**
Creacion de datos dentro del conjunto de datos.

In [79]:
reviews['critic'] = 'everyone' #se puede asignar valores dentro del conjunto de datos tambien
reviews['critic']

id
94355     everyone
126883    everyone
119493    everyone
126909    everyone
119752    everyone
            ...
80210     everyone
76487     everyone
86953     everyone
18824     everyone
88999     everyone
Name: critic, Length: 119988, dtype: object

## **02.3. Funciones resumen y Mapas**

### **02.3.1. Funciones resumen**
Sirve para representar los datos de una forma diferente por ende mas util

 - `describe()`: Es un resumen de la columna que se le ha pasado como argumento a este metodo, depende el tipo de variable que este almacenada en la columna cambia la representacion de los datos.

In [95]:
reviews.points.describe() #variable tipo float64

count    119988.000000
mean         88.442236
std           3.092915
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [96]:
reviews.taster_name.describe() #variable tipo objeto

count          95071
unique            19
top       Roger Voss
freq           23560
Name: taster_name, dtype: object

- `mean()`: Devuelve la media de los valores almacenados en la columna que se indique.

In [94]:
reviews.points.mean()

np.float64(88.44223589025569)

- `median()`: devuelve la media de los valores que esten en el eje que se pida.

In [100]:
reviews.points.median()

88.0

- `unique()`: Devuelve los valores unicos que estan en la columna o fila que se pide.

In [83]:
reviews.taster_name.unique()

array(['Roger Voss', 'Virginie Boone', nan, 'Michael Schachner',
       'Anna Lee C. Iijima', 'Paul Gregutt', 'Sean P. Sullivan',
       'Kerin O’Keefe', 'Anne Krebiehl\xa0MW', 'Lauren Buzzeo',
       'Joe Czerwinski', 'Alexander Peartree', 'Matt Kettmann',
       'Jim Gordon', 'Susan Kostrzewa', 'Mike DeSimone', 'Jeff Jenssen',
       'Christina Pickard', 'Carrie Dykes', 'Fiona Adams'], dtype=object)

 - `value_counts()`: Cantidad de veces que aparece un valor de una variable determinada.

In [84]:
reviews.taster_name.value_counts()

taster_name
Roger Voss            23560
Michael Schachner     14046
Kerin O’Keefe          9697
Paul Gregutt           8868
Virginie Boone         8708
Matt Kettmann          5730
Joe Czerwinski         4766
Sean P. Sullivan       4461
Anna Lee C. Iijima     4017
Jim Gordon             3766
Anne Krebiehl MW       3290
Lauren Buzzeo          1700
Susan Kostrzewa        1023
Mike DeSimone           461
Jeff Jenssen            436
Alexander Peartree      383
Carrie Dykes            129
Fiona Adams              24
Christina Pickard         6
Name: count, dtype: int64

### **02.3.2. Mapas**
El término «mapa», tomado de las matemáticas, se refiere a una función que toma un conjunto de valores y los «asigna» a otro conjunto de valores. En la ciencia de datos, a menudo necesitamos crear nuevas representaciones a partir de datos existentes, o transformar los datos del formato en el que se encuentran ahora al formato que queremos que tengan más adelante. Los mapas son los que se encargan de esta tarea, ¡lo que los convierte en elementos extremadamente importantes para llevar a cabo tu trabajo!

- `(lambda p :)`-> Define una funcion rapida e innominada la cual recibe como parametro de entrada p el cual es un valor individual o un elemento de la serie.

- `(p - review_points_mean)`-> Le resta dicho valor p a la variable `review_points_mean`.

In [90]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)

id
94355    -3.442236
126883   -1.442236
119493   -2.442236
126909   -2.442236
119752   -1.442236
            ...
80210     1.557764
76487    -0.442236
86953     1.557764
18824    -1.442236
88999     1.557764
Name: points, Length: 119988, dtype: float64

- Devuelve una tabla la cual tien alterada los valores de la columna "points".
- Se puede cambiar el valor de `axis` para que en vez de ir por columnas vaya por filas (`axis=index`).
- `apply` conmuta cambios en la tabla segun los valores que se le pasen.

In [91]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?,critic
id,,,,,,,,,,,,,,,
94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,-3.442236,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN,everyone
126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,-1.442236,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN,everyone
119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,-2.442236,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN,everyone
126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,-2.442236,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN,everyone
119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,-1.442236,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,1.557764,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN,everyone
76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,-0.442236,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN,everyone
86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,1.557764,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN,everyone
18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,-1.442236,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN,everyone
88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,1.557764,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN,everyone

- Realiza lo mismo que en anterior apartado pero con las operaciones integradas en Pandas, por lo tanto estas contienen unos metodos mas optimizados y por ende son mas rapidos y eficientes.

In [93]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

id
94355    -3.442236
126883   -1.442236
119493   -2.442236
126909   -2.442236
119752   -1.442236
            ...
80210     1.557764
76487    -0.442236
86953     1.557764
18824    -1.442236
88999     1.557764
Name: points, Length: 119988, dtype: float64

- En este código estamos realizando una operación entre muchos valores en el lado izquierdo (todo lo que hay en la serie) y un único valor en el lado derecho (el valor medio). Pandas analiza esta expresión y deduce que lo que queremos hacer es restar ese valor medio de cada valor del conjunto de datos.

- Pandas también sabrá qué hacer si realizamos estas operaciones entre Series de la misma longitud. Por ejemplo, una forma sencilla de combinar la información de país y región en el conjunto de datos sería hacer lo siguiente.

In [98]:
reviews.country + " - " + reviews.region_1

id
94355                                    NaN
126883                      US - North Coast
119493                       US - California
126909              Spain - Ribera del Duero
119752                   Spain - Rías Baixas
                         ...
80210                         Italy - Barolo
76487     Italy - Amarone della Valpolicella
86953     Italy - Colli Orientali del Friuli
18824                     US - Amador County
88999                                    NaN
Length: 119988, dtype: object

Estos operadores son más rápidos que map() o apply(), ya que utilizan las optimizaciones integradas en pandas. Todos los operadores estándar de Python (>, <, ==, etc.) funcionan de esta manera.

Sin embargo, no son tan flexibles como map() o apply(), que permiten realizar operaciones más avanzadas, como aplicar lógica condicional, algo que no se puede hacer solo con la suma y la resta.

## **02.4. Agrupaciones y Filtrado**

### 02.4.1. Analisis por grupos

- `groupby()`: funcion la cual agrupa los valores almacenados en las columnas que se le pasen como argumento a esta funcion.
- `count()`: funcion del grupo de funciones *groupby()* la cual permite contar los valores agrupados.

In [101]:
reviews.groupby('points').points.count()

points
80       397
81       689
82      1814
83      2963
84      6225
85      9067
86     11526
87     15279
88     15291
89     11147
90     13893
91     10559
92      8951
93      6170
94      3625
95      1514
96       521
97       228
98        77
99        33
100       19
Name: points, dtype: int64

- `size()`: en este contexto hace lo mismo que *count()* pero es mas escueto en algunos aspectos.

In [148]:
reviews.groupby('points').size()

points
80       397
81       689
82      1814
83      2963
84      6225
85      9067
86     11526
87     15279
88     15291
89     11147
90     13893
91     10559
92      8951
93      6170
94      3625
95      1514
96       521
97       228
98        77
99        33
100       19
dtype: int64

- `min()`: funcion del grupo de funciones de *groupby()* la cual sirve para devolver los minimos dentro de un grupo.
- `reviews.groupby('points').price.min()`: Se entiende como agrupar por el valor de los puntos, el valor de la columna de precios, y de esa columna de precios devuelve el minimo valor que se asocie a la columna de puntos.

>Interpretacion de la IA para mas ayuda al entendimiento de esta parte:
>* **`reviews.groupby('points')`**: Separa la estructura de datos en grupos según los valores únicos de la columna **`points`**.
>* **`.price`**: Selecciona únicamente la columna de precios para cada uno de los grupos formados.
>* **`.min()`**: Calcula el valor más bajo dentro de la columna de precios para cada grupo.
>
> El resultado es una Serie de Pandas donde el índice son los puntajes de la columna **`points`** y sus valores asociados son los precios mínimos encontrados para cada puntaje.

In [128]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

Podemos considerar que cada grupo que generamos es una sección de nuestro DataFrame que contiene únicamente datos con valores coincidentes. Podemos acceder directamente a este DataFrame mediante el método *apply()*, y a continuación podemos manipular los datos como mejor nos parezca. Por ejemplo, esta es una forma de seleccionar el nombre del primer vino reseñado de cada bodega del conjunto de datos:

In [129]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

/tmp/ipykernel_9243/506966275.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                   10 Knots 2006 Beachcomber White (Paso Robles)
100 Percent Wine       100 Percent Wine 2014 All Profits to Charity S...
1000 Stories           1000 Stories 2014 Bourbon Barrel Aged Batch No...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2011 Trocken Spätburgunder...
àMaurice               àMaurice 2010 Night Owl Red (Walla Walla Valle...
Štoka                                    Štoka 2011 Izbrani Teran (Kras)
Length: 16757, dtype: object

Se puede tener un control mas precioso, tambien se puede agrupar por mas de una columna, un ejemplo de esto esta en el siguiente bloque de codigo.

In [130]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

/tmp/ipykernel_9243/1865732994.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           Dense, cedary, rubbery aromas of blackberry an...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                                    Massimo Deicas      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico           130.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2008 Massimo Deicas Tannat (Jua...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery  \
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                          Tannat        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

                            dupe?    critic
country   province
Argentina Mendoza Province    NaN  everyone
          Other               NaN  everyone
Armenia   Armenia             NaN  everyone
Australia Australia Other     NaN  everyone
          New South Wales     NaN  everyone
...                           ...       ...
Uruguay   Juanico             NaN  everyone
          Montevideo          NaN  everyone
          Progreso            NaN  everyone
          San Jose            NaN  everyone
          Uruguay             NaN  everyone

[425 rows x 15 columns]

- `agg()`: pertenece al grupo de funciones de *groupby()* esta en especifico permite ejecutar diferentes funciones en el DataFrame de forma simultanea.

In [149]:
reviews.groupby(['country']).price.agg([len, "min", "max"])

                          len   min     max
country
Argentina                3544   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2197   5.0   850.0
Austria                  3034   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     49  10.0    60.0
Bulgaria                  132   8.0   100.0
Canada                    226  12.0   120.0
Chile                    4184   5.0   400.0
China                       1  18.0    18.0
Croatia                    70  12.0    65.0
Cyprus                     10  11.0    21.0
Czech Republic             11  15.0    45.0
Egypt                       1   NaN     NaN
England                    63  25.0    95.0
France                  20353   5.0  3300.0
Georgia                    76   9.0    40.0
Germany                  1992   5.0   775.0
Greece                    432   8.0    79.0
Hungary                   129  10.0   764.0
India                       8  10.0    20.0
Israel                    466   8.0   150.0
Italy                   17940   5.0   900.0
Lebanon                    32  13.0    75.0
Luxembourg                  5  16.0    30.0
Macedonia                  11  15.0    20.0
Mexico                     68   8.0   108.0
Moldova                    56   8.0    42.0
Morocco                    24  14.0    40.0
New Zealand              1278   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5256   5.0  1000.0
Romania                   102   4.0   320.0
Serbia                      8  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   77   7.0    90.0
South Africa             1301   5.0   330.0
Spain                    6116   4.0   770.0
Switzerland                 6  21.0   160.0
Turkey                     81  14.0   120.0
US                      50457   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                    98  10.0   130.0

### **02.4.2. Indices multiples**

Los indices multiples se diferencian de los indices normales porque estos tienen varios niveles.

In [141]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3038
          Other              506
Armenia   Armenia              2
Australia Australia Other    231
          New South Wales     82
...                          ...
Uruguay   Juanico             11
          Montevideo          10
          Progreso            11
          San Jose             3
          Uruguay             23

[425 rows x 1 columns]

In [142]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

Los índices múltiples cuentan con varios métodos para gestionar su estructura por niveles, que no existen en los índices de un solo nivel. Además, requieren dos niveles de etiquetas para recuperar un valor. Gestionar los resultados de los índices múltiples suele ser una «trampa» habitual para los usuarios que se inician en pandas.

Los casos de uso de un índice múltiple se detallan junto con las instrucciones para utilizarlos en la sección «MultiIndex / Advanced Selection» de la documentación de pandas.

Sin embargo, en general, el método de índice múltiple que utilizarás con más frecuencia es el que sirve para volver a convertirlo en un índice normal, el método `reset_index()`.

In [143]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3038
1    Argentina             Other   506
2      Armenia           Armenia     2
3    Australia   Australia Other   231
4    Australia   New South Wales    82
..         ...               ...   ...
420    Uruguay           Juanico    11
421    Uruguay        Montevideo    10
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    23

[425 rows x 3 columns]

### **02.4.3. Filtrado**

Usando la tabla que se genero en el indice multiple anterior, como se puede comprobar los valores de dicha tabla no estaban ordenados, por lo tanto se pued usar *sort_values()* para realizar esta ordenacion.

- `sort_values()`: funcion del grupo de funciones *groupby()* la cual permite ordenar la tabla por un valor que se le adjunta como clave del orden.

In [144]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country           province    len
386        Turkey  Elazığ-Diyarbakir      1
389        Turkey        Urla-Thrace      1
395            US             Hawaii      1
357  South Africa    Piekenierskloof      1
354  South Africa         Paardeberg      1
..            ...                ...    ...
409            US             Oregon   4929
227         Italy            Tuscany   5391
118        France           Bordeaux   5556
415            US         Washington   7965
392            US         California  33656

[425 rows x 3 columns]

La función *sort_values()* ordena por defecto de forma ascendente, es decir, los valores más bajos aparecen primero. Sin embargo, la mayoría de las veces queremos una ordenación descendente, en la que los números más altos aparezcan primero.

In [145]:
countries_reviewed.sort_values(by='len', ascending=False)

    country          province    len
392      US        California  33656
415      US        Washington   7965
118  France          Bordeaux   5556
227   Italy           Tuscany   5391
409      US            Oregon   4929
..      ...               ...    ...
389  Turkey       Urla-Thrace      1
48   Canada      Canada Other      1
40   Brazil  Serra do Sudeste      1
395      US            Hawaii      1
399      US          Kentucky      1

[425 rows x 3 columns]

Se puede filtrar mas de una columna a la vez.

In [146]:
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   506
0    Argentina  Mendoza Province  3038
2      Armenia           Armenia     2
6    Australia          Tasmania    36
4    Australia   New South Wales    82
..         ...               ...   ...
421    Uruguay        Montevideo    10
420    Uruguay           Juanico    11
422    Uruguay          Progreso    11
424    Uruguay           Uruguay    23
419    Uruguay         Canelones    35

[425 rows x 3 columns]

## **02.5. Tipos de datos y valores vacios o perdidos**